### ISSUE TITLE
Does not parse Associated Stim to "itemReport" 

### ISSUE THREAD

**Issue by upretip** [SmarterApp/TabulateSmarterTestContentPackage#55]
The current tabulator output for **ItemReport.csv** does not output _AssociatedStim_ (or Stim: ITS ID). Same for _Tutorial ID_. However _Wordlist ID_ is reported.

Example: `ItemID = 61836`, `StimID = 1961`,` TutorialID = 67865`

@bredd Let me know if you need more details.

**Comment by upretip** [comment]
In addition, the `TransGlos` variable looks to have counts of languages instead of language list. An older version of tabulator showed list of language rather than count.

**Comment by bredd** [comment]
Resolved in v3.0.1.
